### ISSUE TITLE
typeError: Unsupported format:color

### ISSUE THREAD

**Issue by justinday123** [Sense-X/HoP#11]
hi. i got on error, but i have no idea to fix it.
Traceback (most recent call last):
  File "tools/train.py", line 288, in <module>
    main()
  File "tools/train.py", line 277, in main
    train_model(
  File "/workspace/HoP/mmdet3d/apis/train.py", line 344, in train_model
    train_detector(
  File "/workspace/HoP/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/HoP/mmdet3d/datasets/custom_3d.py", line 435, in __getitem__
    data = self.prepare_train_data(idx)
  File "/workspace/HoP/mmdet3d/datasets/custom_3d.py", line 229, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/workspace/HoP/mmdet3d/datasets/pipelines/compose.py", line 49, in __call__
    data = t(data)
  File "/workspace/HoP/mmdet3d/datasets/pipelines/loading.py", line 1130, in __call__
    results['img_inputs'] = self.get_inputs(results)
  File "/workspace/HoP/mmdet3d/datasets/pipelines/loading.py", line 1019, in get_inputs
    img = self.load_image(filename)
  File "/workspace/HoP/mmdet3d/datasets/pipelines/loading.py", line 1151, in load_image
    img_array = load_fun(filename, color_type)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/fileio/io.py", line 51, in load
    raise TypeError(f'Unsupported format: {file_format}')
TypeError: Unsupported format: color

**Comment by CaraJ7** [comment]
Hi @justinday123 , thanks for your feedback.

We fix the bug. It should work fine now. Please refer to #8 for more details.

**Comment by justinday123** [comment]
i got an another issue
Traceback (most recent call last):
  File "tools/train.py", line 288, in <module>
    main()
  File "tools/train.py", line 277, in main
    train_model(
  File "/workspace/hyundai/HoP/mmdet3d/apis/train.py", line 344, in train_model
    train_detector(
  File "/workspace/hyundai/HoP/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/opt/conda/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/workspace/hyundai/HoP/mmdet3d/models/detectors/base.py", line 60, in forward
    return self.forward_train(**kwargs)
  File "/workspace/hyundai/HoP/mmdet3d_plugin/hop/detectors/hop_bevdet.py", line 399, in forward_train
    img_feats, pts_feats, depth, prev_feats = self.extract_feat(
  File "/workspace/hyundai/HoP/mmdet3d_plugin/hop/detectors/hop_bevdet.py", line 184, in extract_feat
    img_feats, depth, prev_feats = self.extract_img_feat(img, img_metas, **kwargs)
  File "/workspace/hyundai/HoP/mmdet3d_plugin/hop/detectors/hop_bevdet.py", line 231, in extract_img_feat
    bev_feat, depth = self.prepare_bev_feat(*inputs_curr)
  File "/workspace/hyundai/HoP/mmdet3d_plugin/hop/detectors/hop_bevdet.py", line 142, in prepare_bev_feat
    bev_feat, depth = self.img_view_transformer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/hyundai/HoP/mmdet3d/models/necks/view_transformer.py", line 697, in forward
    return self.view_transform(input, depth, tran_feat)
  File "/workspace/hyundai/HoP/mmdet3d/models/necks/view_transformer.py", line 285, in view_transform
    return self.view_transform_core(input, depth, tran_feat)
  File "/workspace/hyundai/HoP/mmdet3d/models/necks/view_transformer.py", line 276, in view_transform_core
    coor = self.get_lidar_coor(*input[1:7])
  File "/workspace/hyundai/HoP/mmdet3d/models/necks/view_transformer.py", line 132, in get_lidar_coor
    points = torch.inverse(post_rots).view(B, N, 1, 1, 1, 3, 3)\
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`


how could i solve it?
i'm using CUDA 11.1

**Comment by CaraJ7** [comment]
Hi, the problem seems to be related to your environment. Maybe this [link](https://github.com/facebookresearch/pytorch3d/issues/1399) can be of help.
